trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    docker build -t <your_container_registry>/backend:$(Build.BuildId) .
    docker push <your_container_registry>/backend:$(Build.BuildId)
  displayName: 'Build and Push Docker Image'

- task: AzureWebAppContainer@1
  inputs:
    azureSubscription: '<your_subscription>'
    appName: '<your_app_name>'
    containers: '$(Build.BuildId)’